// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Radar.Api.Data;

#nullable disable

namespace Radar.Api.Data.Migrations
{
    [DbContext(typeof(RadarDbContext))]
    [Migration("20260814121713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Radar.Api.Data.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Locator")
                        .IsUnique();

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Radar.Api.Data.SourceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalLocator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "CanonicalLocator")
                        .IsUnique();

                    b.ToTable("SourceItems");
                });

            modelBuilder.Entity("Radar.Api.Data.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Radar.Api.Data.StorySourceItem", b =>
                {
                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembershipMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MembershipReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("StoryId", "SourceItemId");

                    b.HasIndex("SourceItemId");

                    b.ToTable("StorySourceItems");
                });

            modelBuilder.Entity("Radar.Api.Data.SourceItem", b =>
                {
                    b.HasOne("Radar.Api.Data.Source", "Source")
                        .WithMany("Items")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Radar.Api.Data.StorySourceItem", b =>
                {
                    b.HasOne("Radar.Api.Data.SourceItem", "SourceItem")
                        .WithMany("StoryMemberships")
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Radar.Api.Data.Story", "Story")
                        .WithMany("SourceItems")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceItem");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Radar.Api.Data.Source", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Radar.Api.Data.SourceItem", b =>
                {
                    b.Navigation("StoryMemberships");
                });

            modelBuilder.Entity("Radar.Api.Data.Story", b =>
                {
                    b.Navigation("SourceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
